some edit

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -7,19 +7,20 @@
 #	exit 1
 #fi
 
+# password argument
 MYSQL_PASSWORD=$1
 
 # get current date for archive name
 DATE=$(date +'%d-%m-%Y')
 
 # create dump with all databases
-sudo mysqldump -u root -p"$MYSQL_PASSWORD" --all-databases > "backup.sql"
+mysqldump -u root -p"$MYSQL_PASSWORD" --all-databases > backup.sql
 
 #check if mysql dump was successful
-if [ $? -ne 0 ]; then
-	echo "mysql dump failed, exiting.."
-	exit 1
-fi
+#if [ $? -ne 0 ]; then
+#	echo "mysql dump failed, exiting.."
+#	exit 1
+#fi
 
 # Compress MySQL dump to tar.gz archive
-sudo tar -czvf "$DATE.tar.gz" "backup.sql"
+tar -czvf "$DATE.tar.gz" backup.sql
